//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Ifx.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_MESSAGE_OPTIONS             101
#define IDD_INPUT_CONTROL               102
#define IDD_IPLISTDLG                   103
#define IDD_PATH_OPTIONS                104
#define IDD_TERMINAL_OPTIONS            105
#define IDD_MISC_OPTIONS                106
#define IDD_TERMINAL_FORE_COLORS        107
#define IDD_FORE_COLORS                 109
#define IDD_BACK_COLORS                 110
#define IDD_SESSION_INFO                111
#define IDD_SESSION_NOTES               112
#define IDD_LOG                         113
#define IDD_ACTION_LIST                 114
#define IDD_ACTION_EDIT                 115
#define STATUS_WINDOW_ID                115
#define IDD_ALIAS_EDIT                  116
#define INPUT_WINDOW_ID                 116
#define IDD_BARITEM_EDIT                117
#define TERM_WINDOW_ID                  117
#define IDD_VAR_EDIT                    118
#define ID_TIMER_SOUND                  118
#define IDD_EVENT_EDIT                  119
#define SPLITTER_WINDOW_ID              119
#define IDD_GAG_EDIT                    120
#define IDD_SUB_EDIT                    121
#define IDD_MACRO_EDIT                  122
#define IDD_HIGH_EDIT                   123
#define IDD_ACTION_LISTDLG              124
#define IDD_ALIAS_LISTDLG               125
#define IDD_SCRIPT_PROGRESS             126
#define IDD_VBSCRIPT_TEST               127
#define IDD_EVENT_LISTDLG               128
#define IDR_IFX                         129
#define IDR_MAINFRAME                   130
#define IDR_IFXTYPE                     131
#define IDR_CONTEXT_MENU                132
#define IDR_POPUP_TOOLBAR               133
#define IDR_MENU_IMAGES                 134
#define IDR_SESSMGRTYPE                 135
#define IDR_INPUTMENU                   136
#define IDR_POPUP_MENU                  137
#define IDR_CHAT_MGR_MENU               138
#define IDB_CHECK                       139
#define IDR_TRAY_MENU1                  139
#define IDB_WORKSPACE                   140
#define IDB_CATEGORY                    141
#define IDB_SPLASH                      142
#define IDB_BANNER                      143
#define IDB_CHAT_TREE_BMP               144
#define IDP_OLE_INIT_FAILED             145
#define IDS_MAIN_TOOLBAR                146
#define IDS_IFX_TOOLBAR                 147
#define IDP_SOCKETS_INIT_FAILED         148
#define ID_TIMER_EVENT                  149
#define IDS_VARIABLE_REMOVED            149
#define CG_IDS_PHYSICAL_MEM             150
#define CG_IDS_DISK_SPACE               151
#define CG_IDS_DISK_SPACE_UNAVAIL       152
#define IDR_APPLICATION                 153
#define IDS_INVALID_VARIABLE_INDEX      153
#define IDR_INPUTCALLBACK               154
#define IDS_VARNAME_NOT_FOUND           154
#define IDR_DOCUMENT                    155
#define IDS_WIZARD_HEAD_FACE_NAME       155
#define IDR_DOCUMENTS                   156
#define IDS_BROWSE_HELP_FOLDER          156
#define IDR_SESSIONOBJECT               157
#define IDS_BROWSE_DOWNLOAD_FOLDER      157
#define IDR_XSESSIONINFO                158
#define IDS_BROWSE_UPLOAD_FOLDER        158
#define IDR_MESSAGEOPTIONS              159
#define IDS_BROWSE_SOUND_FOLDER         159
#define IDT_SPEEDWALK                   160
#define IDS_BROWSE_LOG_FOLDER           160
#define IDS_MISSING_CHATNAME            161
#define IDS_MISSING_HELPPATH            162
#define IDS_MISSING_DOWNLOADPATH        163
#define IDS_MISSING_UPLOADPATH          164
#define IDS_MISSING_SOUNDPATH           165
#define IDS_MISSING_LOGPATH             166
#define IDS_INVALID_HELPPATH            167
#define IDS_INVALID_DOWNLOADPATH        168
#define IDS_INVALID_UPLOADPATH          169
#define IDS_INVALID_SOUNDPATH           170
#define IDS_INVALID_LOGPATH             171
#define IDS_EMPTYMUDADDRESS             172
#define IDS_EMPTYCHARACTERNAME          173
#define IDS_EMPTYSOUNDPATH              174
#define IDS_EMPTY_SCRIPT_PATH           175
#define IDS_INVALID_SCRIPT_PATH         176
#define IDS_SESSION_OPTIONS_TITLE       177
#define IDS_EDIT_DEFAULTS               178
#define IDS_LOST_SOCKET_HANDLE          179
#define IDS_CHATSERVER_REMOTE_CLOSED_CONNECTION 180
#define IDS_CHATSERVER_CHAT_CONNECTION_NOT_FOUND 181
#define IDS_CHATSERVER_ERROR_OCCURRED   182
#define IDS_CHATSERVER_FILE_TRANSFER_CANCELED 183
#define IDS_CHATSERVER_PING_REQUEST_SENT 184
#define IDS_CHATSERVER_COMMAND_SENT     185
#define IDS_CHATSERVER_FILE_TRANSFER_ALREADY_IN_PROGRESS 186
#define IDS_CHATSERVER_FILE_TRANSFER_STARTED 187
#define IDS_CHATSERVER_YOU_CHAT_TO_EVERYONE 188
#define IDS_CHATSERVER_CHATS_TO_EVERYONE 189
#define IDS_CHATSERVER_YOU_CHAT_TO_GROUP 190
#define IDS_CHATSERVER_CHATS_TO_GROUP   191
#define IDS_CHATSERVER_YOU_CHAT_TO_PERSON 192
#define IDS_CHATSERVER_CHATS_TO_YOU     193
#define IDS_CHATSERVER_YOU_EMOTE_TO_EVERYONE 194
#define IDS_CHATSERVER_FAILED_TO_CREATE_SOCKET 195
#define IDS_CHATSERVER_YOU_EMOTE_TO_GROUP 196
#define IDS_CHATSERVER_YOU_EMOTE_TO_PERSON 197
#define IDS_CHATSERVER_NAME_CHANGE      198
#define IDS_CHATSERVER_REQUESTED_YOUR_PUBLIC_CONNECTIONS 199
#define IDS_CHATSERVER_CONNECTIONS_RETURNED 200
#define IDS_CHATSERVER_ALREADY_CONNECTED_WITH 201
#define IDS_CHATSERVER_DND_IS_ON        202
#define IDS_CHATSERVER_NOT_ALLOWING_TRANSFERS 203
#define IDS_CHATSERVER_CURRENTLY_TRANSFERRING 204
#define IDS_CHATSERVER_INVALID_PACKET   205
#define IDS_CHATSERVER_FILE_ALREADY_EXISTS 206
#define IDS_CHATSERVER_FILE_BEING_SENT_ALREADY_EXISTS 207
#define IDD_MACRO_LISTDLG               208
#define IDS_CHATSERVER_UNABLE_TO_CREATE_FILE 208
#define IDR_FULLSCREEN                  209
#define IDS_CHATSERVER_FAILED_TO_CREATE_FILE 209
#define IDS_CHATSERVER_RECEIVING_FILE_FROM 210
#define IDS_CHATSERVER_CALLING          211
#define IDS_CHATSERVER_CONNECTION_FAILED 212
#define IDD_BARITEM_LISTDLG             213
#define IDS_CHATSERVER_WAITING_FOR_RESPONSE 213
#define IDD_MSP_OPTIONS                 214
#define IDS_CHATSERVER_CHAT_WAS_DENIED  214
#define IDD_SESSION_NAME_WIZARD_PAGE    215
#define IDD_NEWSESSION_SCRIPT_INFO      215
#define IDS_CHATSERVER_CONNECTION_ACCEPTED 215
#define IDD_ADDRESS_WIZARD_PAGE         216
#define IDD_NEWSESSION_WELCOME          216
#define IDS_CHATSERVER_NEGOTIATION_FAILED 216
#define IDD_SCRIPTINFO_WIZARD_PAGE      217
#define IDC_SPLITTER                    217
#define IDD_NEWSESSION_MUD_PAGE         217
#define IDS_CHATSERVER_ACCEPT_REQUEST_QUESTION 217
#define IDD_FINISHED_WIZARD_PAGE        218
#define IDB_SPLITTER                    218
#define IDD_NEWSESSION_COMPLETE         218
#define IDS_CHATSERVER_CHATREQUEST      218
#define IDD_FIRSTTIME_WELCOME           219
#define IDS_CHATSERVER_CHAT_REQUEST_ACCEPTED 219
#define IDD_FIRSTTIME_COMPLETE          220
#define IDS_CHATSERVER_LOST_SOCKET_HANDLE 220
#define IDD_FIRSTTIME_PATHS             221
#define IDS_CHATSERVER_CHAT_CONNECTION_LOST 221
#define IDB_NEWSESSION_WATERMARK        222
#define IDD_FIRSTTIME_CHAT              222
#define IDS_CHATSERVER_FAILED_TO_ACCEPT_SOCKET 222
#define IDB_BANNER_ICON                 223
#define IDD_DEFAULTS_DIALOG             223
#define IDS_CHATSERVER_FAILED_TO_SET_NONBLOCK 223
#define IDS_CHATSERVER_NEGOTIATING_INCOMING_CHAT 224
#define IDD_MUD_MANAGER                 225
#define IDS_CHATSERVER_FILE_START_DENIED 225
#define IDS_CHATSERVER_FILE_TRANSFER_COMPLETE 226
#define IDD_MACRO_LISTDLG1              226
#define IDS_CHATSERVER_NEGOTIATION_FAILED_S 227
#define IDB_NEW_SMALLBANNER             228
#define IDS_CHATSERVER_PING_RETURNED    228
#define IDS_CHATSERVER_IS_PEEKING_AT_YOUR_CONNECTIONS 229
#define IDS_CHATSERVER_DOESNT_HAVE_OTHER_CONNECTIONS 230
#define IDS_CHATSERVER_CHAT_PEEK_FOUND_CONNECTIONS 231
#define IDS_CHATSERVER_HAS_NOT_GIVEN_PERM_TO_SNOOP 232
#define IDS_CHATSERVER_HAS_STOPPED_SNOOPING_YOU 233
#define IDS_CHATSERVER_YOU_STOPPED_SNOOPING 234
#define IDS_CHATSERVER_YOU_ARE_BEING_SNOOPED_BY 235
#define IDS_CHATSERVER_YOU_HAVE_BEGUN_SNOOPING 236
#define IDS_CHATSERVER_IS_NOT_ALLOWING_COMMANDS 237
#define IDS_CHATSERVER_RECEIVED         238
#define IDS_CHATSERVER_FILE_NOT_FOUND   239
#define IDS_CHATSERVER_CHAT_CONNECTION_S_NOT_FOUND 240
#define IDS_CHATSERVER_CHAT_CONNECTION_S_DISCONNECTED 241
#define IDS_CHATSERVER_NO_NAME_PROVIDED 242
#define IDS_CHATSERVER_ADDRESS_SEGMENT_CORRUPT 243
#define IDS_CHATSERVER_YOU_DO_NOT_HAVE_CONNECTIONS 244
#define IDS_CHATSERVER_NO_FILE_TRANSFER_IN_PROGRESS 245
#define IDS_CHATSERVER_RECEIVING_S_FROM_S 246
#define IDS_CHATSERVER_SENDING_S_TO_S   247
#define IDS_CHATSERVER_FILE_LENGTH_U    248
#define IDS_CHATSERVER_BYTES_RECEIVED_U 249
#define IDS_CHATSERVER_BYTES_REMAINING  250
#define IDS_CHATSERVER_BYTES_PER_SECOND_U 251
#define IDS_CHATSERVER_BYTES_SENT       252
#define IDS_CHATSERVER_NO_LONGER_ACCEPTING_COMMANDS_FROM_S 253
#define IDS_CHATSERVER_S_IS_NO_LONGER_ACCEPTING_COMMANDS_FROM_YOU 254
#define IDS_CHATSERVER_NOW_ACCEPTING_COMMANDS_FROM_S 255
#define IDS_CHATSERVER_S_IS_NOW_ACCEPTING_COMMANDS_FROM_YOU 256
#define IDS_CHATSERVER_NO_LONGER_IGNORING_S 257
#define IDS_CHATSERVER_NOW_IGNORING_S   258
#define IDS_CHATSERVER_S_MARKED_AS_PUBLIC 259
#define IDS_CHATSERVER_S_HAS_MARKED_YOUR_CONNECTION_PUBLIC 260
#define IDS_CHATSERVER_S_MARKED_AS_PRIVATE 261
#define IDS_CHATSERVER_S_HAS_MARKED_YOUR_CONNECTION_PRIVATE 262
#define IDS_CHATSERVER_S_IS_NO_LONGER_BEING_SERVED 263
#define IDS_CHATSERVER_YOU_ARE_NO_LONGER_SERVED_BY_S 264
#define IDS_CHATSERVER_S_IS_BEING_SERVED 265
#define IDS_CHATSERVER_YOU_ARE_BEING_SERVED_BY_S 266
#define IDS_CHATSERVER_S_IS_NO_LONGER_ALLOWED_TO_SNOOP_YOU 267
#define IDS_CHATSERVER_YOU_ARE_NO_LONGER_ALLOWED_TO_SNOOP_S 268
#define IDS_CHATSERVER_S_IS_NOW_ALLOWED_TO_SNOOP_YOU 269
#define IDS_CHATSERVER_YOU_ARE_NOW_ALLOWED_TO_SNOOP_S 270
#define IDS_CHATSERVER_S_IS_NO_LONGER_ALLOWED_TO_SEND_YOU_FILES 271
#define IDS_CHATSERVER_S_IS_NO_LONGER_ACCEPTING_FILE_TRANSFERS_FROM_YOU 272
#define IDS_CHATSERVER_S_IS_ALLOWED_TO_SEND_YOU_FILES 273
#define IDS_CHATSERVER_S_IS_ACCEPTING_FILE_TRANSFERS_FROM_YOU 274
#define IDS_CHATSERVER_ALREADY_STARTED  275
#define IDS_CHATSERVER_STARTING_CHAT_SERVER_ON_PORT_D 276
#define IDD_GAG_LISTDLG                 277
#define ID_INDICATOR_CMDS               277
#define ID_INDICATOR_KBYTES             278
#define IDS_CHATSERVER_EMOTEs_TO_EVERYONE 279
#define IDS_CHATSERVER_EMOTES_TO_EVERYONE 279
#define IDS_CHATSERVER_S_IS_NO_LONGER_BEING_SERVE_EXCLUDED 279
#define IDS_CHATSERVER_EMOTES_TO_GROUP  280
#define IDD_SUBS_LISTDLG                281
#define IDS_CHATSERVER_EMOTES_TO_YOU    281
#define ID_FAST_TIMER                   282
#define IDS_STRING283                   283
#define IDD_HIGH_LISTDLG                284
#define IDC_TERM_FORECOLOR              1001
#define IDC_TERM_BACKCOLOR              1002
#define IDC_CHAT_FORECOLOR              1003
#define IDC_MESSAGE_FORE                1003
#define IDC_INPUT_FONT                  1004
#define IDC_LOCAL_ECHO                  1005
#define IDC_CHAT_BACKCOLOR              1006
#define IDC_MESSAGE_BACK                1006
#define IDC_BAR_BACKCOLOR               1007
#define IDC_SCROLLBACK_BUFFER_SIZE      1008
#define IDC_MESSAGE_FORECOLOR           1009
#define IDC_MESSAGE_BACKCOLOR           1010
#define IDC_COMMAND_BUFFER_SIZE         1011
#define IDC_INPUT_BACKCOLOR             1012
#define IDC_TERM_FONT                   1013
#define IDC_FORE_BLACK                  1014
#define IDC_HIGHLIGHTTEXT               1015
#define IDC_BACK_BLACK                  1015
#define IDC_FORE_GREEN                  1016
#define IDC_HIGHLIGHT                   1017
#define IDC_BACK_GREEN                  1017
#define IDC_TELNET_GA                   1018
#define IDC_FORE_BLUE                   1019
#define IDC_FORE_GRAY                   1020
#define IDC_FORE_CYAN                   1021
#define IDC_FORE_RED                    1022
#define IDC_FORE_MAGENTA                1023
#define IDC_FORE_BROWN                  1024
#define IDC_FORE_LIGHTRED               1025
#define IDC_FORE_LIGHTMAGENTA           1026
#define IDC_FORE_YELLOW                 1027
#define IDC_FORE_WHITE                  1028
#define IDC_FORE_DARKGRAY               1029
#define IDC_FORE_LIGHTBLUE              1030
#define IDC_FORE_LIGHTGREEN             1031
#define IDC_FORE_LIGHTCYAN              1032
#define IDC_IPLIST                      1033
#define IDC_BACK_BLUE                   1033
#define IDC_INPUT_CTRL                  1034
#define IDC_BACK_CYAN                   1034
#define IDC_ACTION_MESSAGES             1035
#define IDC_BACK_RED                    1035
#define IDC_ALIAS_MESSAGES              1036
#define IDC_BACK_MAGENTA                1036
#define IDC_DOWNLOAD_PATH               1037
#define IDC_BACK_BROWN                  1037
#define IDC_ARRAY_MESSAGES              1038
#define IDC_BACK_GRAY                   1038
#define IDC_UPLOAD_PATH                 1039
#define IDC_STATUSBARITEM_MESSAGES      1040
#define IDC_SOUND_PATH                  1041
#define IDC_ENABLE_MESSAGES             1042
#define IDC_SESSION_PATH                1043
#define IDC_EVENT_MESSAGES              1044
#define IDC_LOG_PATH                    1045
#define IDC_GAG_MESSAGES                1046
#define IDC_PICK_DOWNLOAD               1047
#define IDC_VAR_MESSAGE                 1048
#define IDC_PICK_LOG                    1049
#define IDC_HIGH_MESSAGES               1050
#define IDC_PICK_SESSION                1051
#define IDC_LISTITEM_MESSAGES           1052
#define IDC_PICK_SOUND                  1053
#define IDC_LIST_MESSAGES               1054
#define IDC_PICK_UPLOAD                 1055
#define IDC_MACRO_MESSAGES              1056
#define IDC_SUB_MESSAGES                1057
#define IDC_TAB_MESSAGES                1058
#define IDC_IGNORE_ACTIONS              1059
#define IDC_IGNORE_GAGS                 1060
#define IDC_IGNORE_HIGHS                1061
#define IDC_IGNORE_SUBS                 1062
#define IDC_IGNORE_ALL                  1063
#define IDC_SBB_SPNNER                  1064
#define IDC_ZMUD_RETENT                 1065
#define IDC_AUTO_ACCEPT                 1066
#define IDC_CHB_SPNNER                  1067
#define IDC_CHAT_NAME                   1068
#define IDC_CHAT_PORT                   1069
#define IDC_STAT_FONT                   1070
#define IDC_STAT_FORECOLOR              1071
#define IDC_STAT_BACKCOLOR              1072
#define IDC_DND                         1073
#define IDC_SESSION_NAME                1074
#define IDC_SESSION_ADDRESS             1075
#define IDC_SESSION_PORT                1076
#define IDC_IGNORE_ALIASES              1077
#define IDC_MAXIMIZE                    1078
#define IDC_PRESUB                      1079
#define IDC_EVENTS                      1080
#define IDC_PROMPT_OVERWRITE            1081
#define IDC_STATUSBAR                   1082
#define IDC_SPEEDWALK                   1083
#define IDC_CHAT_SERVER                 1084
#define IDC_PACE                        1085
#define IDC_NOTES                       1086
#define IDC_NOTE_LIST                   1087
#define IDC_SCRIPT_PATH                 1088
#define IDC_SCRIPT_BROWSE               1089
#define IDC_AUTO_LOADSCRIPT             1090
#define IDC_AUTO_LOG                    1091
#define IDC_LOG_FILENAME                1092
#define IDC_LOGFILE_BROWSE              1093
#define IDC_APPEND_LOG                  1094
#define IDC_LOG_FILE_NAME               1095
#define IDC_INCLUDE_SCROLLBACK          1096
#define IDC_BROWSE_LOGFILE              1097
#define IDC_CLOSE_LOG                   1098
#define IDC_PHYSICAL_MEM                1099
#define IDC_DISK_SPACE                  1100
#define IDC_ACTION_GROUPS               1101
#define IDC_TRIGGER                     1102
#define IDC_ACTION                      1103
#define IDC_GROUP                       1104
#define IDC_DISABLED                    1105
#define IDC_ALIAS_TEXT                  1106
#define IDC_ALIAS_ACTION                1107
#define IDC_ALIAS_GROUP                 1108
#define IDC_ALIAS_DISABLED              1109
#define IDC_SEPARATOR                   1110
#define IDC_POSITION                    1112
#define IDC_LENGTH                      1113
#define IDC_NAME                        1114
#define IDC_TEXT                        1115
#define IDC_BAR_FORECOLOR               1117
#define IDC_VAR_NAME                    1118
#define IDC_VAR_VALUE                   1119
#define IDC_VAR_GROUP                   1120
#define IDC_EVENT_DISABLED              1121
#define IDC_EVENT_SECONDS               1122
#define IDC_EVENT_NAME                  1123
#define IDC_EVENT_ACTION                1124
#define IDC_EVENT_GROUP                 1125
#define IDC_GAG_MASK                    1126
#define IDC_GAG_GROUP                   1127
#define IDC_WEBSITE_BTN                 1129
#define IDC_SUB_MASK                    1130
#define IDC_SUB_SUB                     1131
#define IDC_SUB_GROUP                   1132
#define IDC_SUB_DISABLED                1133
#define IDC_MACRO_DISABLED              1134
#define IDC_MACRO_KEY                   1136
#define IDC_SEND_TO_MUD                 1137
#define IDC_INPUT_CONTROL               1138
#define IDC_INPUT_CONTROLCR             1139
#define IDC_HIGH_MASK                   1140
#define IDC_HIGH_GROUP                  1141
#define IDC_FORE_COLOR                  1142
#define IDC_BACK_COLOR                  1143
#define IDC_ACTIONLIST                  1145
#define IDC_BTN_ADD_ACTION              1146
#define IDC_BTN_EDIT_ACTION             1147
#define IDC_BTN_DELETE_ACTION           1148
#define IDC_ALIASLIST                   1149
#define IDC_TRIGGER_STATIC              1150
#define IDC_ACTION_STATIC               1151
#define IDC_GROUP_STATIC                1152
#define IDC_PROGRESS1                   1153
#define IDC_CODE                        1154
#define IDC_EVENT_LIST                  1155
#define IDC_EVENT_ADD                   1156
#define IDC_EVENT_EDIT                  1157
#define IDC_EVENT_DELETE                1158
#define IDC_SUB_DEPTH                   1159
#define IDC_SHOW_INFO                   1160
#define IDC_MACRO_LIST                  1161
#define IDC_MACRO_ADD                   1162
#define IDC_MACRO_EDIT                  1163
#define IDC_MACRO_DELETE                1164
#define IDC_MMSTATUSCTRL1               1165
#define IDC_BARITEM_LIST                1166
#define IDC_BTN_ADD_BARITEM             1167
#define IDC_BTN_EDIT_BARITEM            1168
#define IDC_BTN_DELETE_BARITEM          1169
#define IDC_PROCESS_MUSIC               1170
#define IDC_PROCESS_SOUND               1171
#define IDC_USE_MSP                     1172
#define IDC_DX_80                       1173
#define IDC_PLAYSOUND                   1174
#define IDC_DEBUG_MSP_TRIGGERS          1175
#define IDC_EDIT1                       1176
#define IDC_EDIT2                       1177
#define IDC_MUD_ADDRESS                 1177
#define IDC_CHECK1                      1178
#define IDC_RUN_CHARACTER_SETUP         1178
#define IDC_IDC_MUD_PORT                1178
#define IDC_CONNECT_NOW                 1178
#define IDC_MAX_WIDTH                   1178
#define IDC_CHECK2                      1179
#define IDC_SOUND_FOLDER                1179
#define IDC_END_OF_LINE_DETECT          1179
#define IDC_DEFAULT_CHECK               1179
#define IDC_MAX_HEIGHT                  1179
#define IDC_FULLSCREEN                  1180
#define IDC_LOG_FOLDER                  1180
#define IDC_DOCK_RIGHT                  1180
#define IDC_TIMESTAMP_LOG               1181
#define IDC_ALIAS_TEXT_LABEL            1182
#define IDC_ACTION_LABEL                1183
#define IDC_VERSION                     1184
#define IDC_GROUP_LABEL                 1184
#define IDC_NAME_LABEL                  1185
#define IDC_SECONDS_LABEL               1186
#define IDC_KEY_LABEL                   1187
#define IDC_DEST_GROUP                  1188
#define IDC_TEXT_LABEL                  1189
#define IDC_POSITION_LABEL              1190
#define IDC_LENGTH_LABEL                1191
#define IDC_FORE_LABEL                  1192
#define IDC_BACK_LABEL                  1193
#define IDC_BUTTON1                     1194
#define IDC_CLOSE                       1194
#define IDC_BROWSE_FOR_SCRIPT           1194
#define IDC_BROWSE_DEFAULT              1194
#define IDC_WELCOME_HEAD                1195
#define IDC_BROWSE_DOWNLOAD             1195
#define IDC_WELCOME_BODY                1196
#define IDC_BROWSE_UPLOAD               1196
#define IDC_COMPLETE_HEADER             1197
#define IDC_BROWSE_SOUND                1197
#define IDC_TITLE                       1198
#define IDC_BROWSE_LOG                  1198
#define IDC_HELP_FILES                  1199
#define IDC_DOWNLOAD_FOLDER             1200
#define IDC_UPLOAD_FOLDER               1201
#define IDC_BROWSE_HELP                 1202
#define IDC_CHATNAME                    1203
#define IDC_CHARACTER_NAME              1204
#define IDC_HIGH_LIST                   1204
#define IDC_BROWSE_FOR_MUD              1205
#define IDC_SCRIPT_NAME                 1206
#define IDC_EDIT_DEFAULTS               1207
#define IDC_DEFAULT_SESSION_PATH        1210
#define IDC_HELP_LABEL                  1211
#define IDC_HELP_DESC                   1212
#define IDC_MUD_LIST                    1213
#define IDC_DELETE_BTN                  1215
#define IDC_BUTTON3                     1217
#define IDC_BUTTON4                     1218
#define IDC_BUTTON5                     1219
#define IDC_GAG_LIST                    1220
#define IDC_SCRIPT_HELP_TXT             1220
#define IDC_GAG_ADD                     1221
#define IDC_PROGRESS2                   1221
#define IDC_GAG_EDIT                    1222
#define IDC_SHOWBORDER                  1222
#define IDC_GAG_DELETE                  1223
#define IDC_COMMAND_CHAR                1223
#define IDC_HIGH_ADD                    1224
#define IDC_AUTO_MESSAGES               1224
#define IDC_HIGH_DELETE                 1225
#define IDC_SPIN1                       1225
#define IDC_HIGH_EDIT                   1226
#define IDC_LINE_LENGTH                 1226
#define IDC_SUB_ADD                     1227
#define IDC_SUB_DELETE                  1228
#define IDC_SUB_EDIT                    1229
#define IDC_SUB_LIST                    1230
#define ID_VIEW_CUSTOMIZE               32770
#define ID_VIEW_TOOLBARS                32771
#define ID_POPUP_ANIMATE                32773
#define ID_DEMO_MAXIMISE                32780
#define ID_DEMO_MINIMISE                32781
#define ID_WINDOW_MANAGER               32784
#define ID_VIEW_USER_TOOLBAR1           32793
#define ID_VIEW_USER_TOOLBAR2           32794
#define ID_VIEW_USER_TOOLBAR3           32795
#define ID_VIEW_USER_TOOLBAR4           32796
#define ID_VIEW_USER_TOOLBAR5           32797
#define ID_VIEW_USER_TOOLBAR6           32798
#define ID_VIEW_USER_TOOLBAR7           32799
#define ID_VIEW_USER_TOOLBAR8           32800
#define ID_VIEW_USER_TOOLBAR9           32801
#define ID_VIEW_USER_TOOLBAR10          32802
#define ID_VIEW_WORKSPACE               32803
#define ID_VIEW_OUTPUT                  32804
#define ID_TOOLS_ENTRY                  32805
#define ID_USER_TOOL1                   32806
#define ID_USER_TOOL2                   32807
#define ID_USER_TOOL3                   32808
#define ID_USER_TOOL4                   32809
#define ID_USER_TOOL5                   32810
#define ID_USER_TOOL6                   32811
#define ID_USER_TOOL7                   32812
#define ID_USER_TOOL8                   32813
#define ID_USER_TOOL9                   32814
#define ID_USER_TOOL10                  32815
#define ID_VIEW_OPTIONS                 32816
#define ID_TOOLS_MACRO                  32816
#define ID_SESSION_CONNECT              32817
#define ID_SESSION_ZAP                  32818
#define ID_ENTER_KEY                    32819
#define ID_FULL_SCREEN                  32820
#define ID_PAGE_DOWN                    32821
#define ID_PAGE_UP                      32822
#define ID_UP_ARROW                     32823
#define ID_DOWN_ARROW                   32824
#define ID_ESCAPE                       32825
#define ID_TAB_KEY                      32826
#define ID_BUTTON32832                  32832
#define ID_SESSION_LOG                  32834
#define ID_SESSION_SAVESCROLLBACK       32835
#define ID_SESSION_READSCRIPT           32836
#define ID_SESSION_STARTCHATSERVER      32837
#define ID_SESSION_STOPCHATSERVER       32838
#define ID_FILE_EXIT                    32840
#define ID_SESSION_NEWSESSION           32843
#define ID_SESSION_EDITSESSION          32844
#define ID_SESSION_DELETESESSION        32845
#define ID_SESSION_LAUNCHSESSION        32846
#define ID_CATEGORIES_NEWCATEGORY       32847
#define ID_CATEGORIES_EDITCATEGORY      32848
#define ID_CATEGORIES_DELETECATEGORY    32849
#define ID_INPUTCONTEXT_COPY            32850
#define ID_INPUTCONTEXT_CUT             32851
#define ID_INPUTCONTEXT_PASTE           32852
#define ID_SESSION_CONFIGURATION        32853
#define ID_CONFIGURATION_DEFAULTSESSION 32854
#define ID_HELP_SENDBUGREPORT           32855
#define ID_CONFIGURATION_ACTIONSTRIGGERS 32856
#define ID_VIEW_CAPTIONS                32857
#define ID_FORCE_GRADIENT               32858
#define ID_CONFIGURATION_ACTIONS        32871
#define ID_BUTTON32872                  32872
#define ID_CONFIGURATION_ALIASES        32873
#define ID_SESSION_TESTVBSCRIPT         32874
#define ID_POPUP_SENDFILE               32875
#define ID_POPUP_MARKPRIVATE            32876
#define ID_POPUP_ALLOWCOMMANDS          32877
#define ID_POPUP_ALLOWTRANSFERS         32878
#define ID_POPUP_IGNORE                 32879
#define ID_POPUP_SERVE                  32880
#define ID_POPUP_ALLOWSNOOP             32881
#define ID_POPUP_SNOOP                  32882
#define ID_CONFIGURATION_EVENTS         32883
#define ID_POPUP_UNCHAT                 32884
#define ID_POPUP_PING                   32885
#define ID_POPUP_REQUESTCONNECTIONS     32886
#define ID_POPUP_PEEKCONNECTIONS        32887
#define ID_BUTTON32891                  32891
#define ID_CONFIGURATION_MACROS         32893
#define ID_CONFIGURATION_SELECTSKIN     32895
#define ID_CONFIGURATION_STATUSBARITEMS 32897
#define ID_WINDOW_DESKTOP               32899
#define ID_VIEW_TABBEDWINDOWS           32900
#define ID_FILE_WIZARD                  32901
#define ID_Menu                         32904
#define ID_FILE_EDITDEFAULTS            32905
#define ID_FILE_EDITDEFAULTS32906       32906
#define ID_HELP_HELPFORMUDMASTER2000    32908
#define ID_HELP_HELPFORMUDMASTER2001    32909
#define ID_SCRIPT_GAGS                  32910
#define ID_BUTTON32911                  32911
#define ID_SCRIPT_SUBSTITUTIONS         32913
#define ID_SCRIPT_HIGHLIGHTS            32914
#define ID_BUTTON32916                  32916
#define ID_RAW_MUD_LOG                  32918
#define ID_ALIAS_TREE                   32919
#define ID_HELP_SCRIPTFORUMFORMUDMASTER2K6 32923
#define ID_TOOLBAR_SCROLLBARS           32925
#define ID_VIEW_SCROLLBARS              32926
#define ID_WINDOW_SAVE_POSITION         32930
#define ID_MACRO_START                  42000
#define ID_MACRO_1                      42001
#define ID_MACRO_2                      42002
#define ID_MACRO_3                      42003
#define ID_MACRO_4                      42004
#define ID_MACRO_5                      42005
#define ID_MACRO_6                      42006
#define ID_MACRO_7                      42007
#define ID_MACRO_8                      42008
#define ID_MACRO_9                      42009
#define ID_MACRO_10                     42010
#define ID_MACRO_11                     42011
#define ID_MACRO_12                     42012
#define ID_MACRO_13                     42013
#define ID_MACRO_14                     42014
#define ID_MACRO_15                     42015
#define ID_MACRO_16                     42016
#define ID_MACRO_17                     42017
#define ID_MACRO_18                     42018
#define ID_MACRO_19                     42019
#define ID_MACRO_20                     42020
#define ID_MACRO_21                     42021
#define ID_MACRO_22                     42022
#define ID_MACRO_23                     42023
#define ID_MACRO_24                     42024
#define ID_MACRO_25                     42025
#define ID_MACRO_26                     42026
#define ID_MACRO_27                     42027
#define ID_MACRO_28                     42028
#define ID_MACRO_29                     42029
#define ID_MACRO_30                     42030
#define ID_MACRO_31                     42031
#define ID_MACRO_32                     42032
#define ID_MACRO_33                     42033
#define ID_MACRO_34                     42034
#define ID_MACRO_35                     42035
#define ID_MACRO_36                     42036
#define ID_MACRO_37                     42037
#define ID_MACRO_38                     42038
#define ID_MACRO_39                     42039
#define ID_MACRO_40                     42040
#define ID_MACRO_41                     42041
#define ID_MACRO_42                     42042
#define ID_MACRO_43                     42043
#define ID_MACRO_44                     42044
#define ID_MACRO_45                     42045
#define ID_MACRO_46                     42046
#define ID_MACRO_47                     42047
#define ID_MACRO_48                     42048
#define ID_MACRO_49                     42049
#define ID_MACRO_50                     42050
#define ID_MACRO_END                    43051
#define ID_INDICATOR_IP                 44142
#define IDS_MSGBOX_TITLE                44446
#define IDS_DOWNLOAD_TITLE              44447
#define IDS_LOG_TITLE                   44448
#define IDS_SESSION_TITLE               44449
#define IDS_SOUND_TITLE                 44450
#define IDS_UPLOAD_TITLE                44451
#define ID_EXT_WINDOW_COMMAND           45052
#define ID_EXT_WINDOW_TEXT              45053
#define ID_INDICATOR_ONLINE             49143

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        230
#define _APS_NEXT_COMMAND_VALUE         32931
#define _APS_NEXT_CONTROL_VALUE         1227
#define _APS_NEXT_SYMED_VALUE           171
#endif
#endif
